/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ColumnConfigTable: typeof import('./../src/ws-edit-table/components/ColumnConfigTable.vue')['default']
    LessButton: typeof import('./../src/less-button/LessButton.vue')['default']
    SetSampleDefault: typeof import('./../src/ws-edit-table/components/SetSampleDefault.vue')['default']
    TailwindButton: typeof import('./../src/tailwind-button/TailwindButton.vue')['default']
    WsEditTable: typeof import('./../src/ws-edit-table/WsEditTable.vue')['default']
    WsLinesChart: typeof import('./../src/ws-lines-chart/WsLinesChart.vue')['default']
    WsModal: typeof import('./../src/ws-modal/WsModal.vue')['default']
  }
}
